services:
  db:
    image: postgres:16
    container_name: proyecto0-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyecto0
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto0-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://proyecto0:proyecto0@db:5432/proyecto0?sslmode=disable
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.proxy
    container_name: proyecto0-frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: {}

networks:
  default:
    name: proyecto0-network
