services:
  db:
    image: postgres:16
    container_name: proyecto0-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto0-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://proyecto0:proyecto0@db:5432/proyecto0?sslmode=disable}
      PORT: ${PORT:-8080}
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.proxy
    container_name: proyecto0-web
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: {}
